version: '2'
services:
  apim:
    container_name: apim
    depends_on: 
      - das
    build: 
        context: .
        dockerfile: apim/Dockerfile
    ports:
     - "9763:9763"
     - "9443:9443"
     - "8280:8280"
     - "8243:8243"
  das:
    container_name: das 
    build:
      context: .
      dockerfile: das/Dockerfile
    ports:
      - "9764:9764"
      - "9444:9444"
      - "7712:7712"
      - "7612:7612"